// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRe0ea0zVKRGSyWdZNW3VbFHluPSo6Oc0',
    appId: '1:681041547372:web:ae6545d0e02b980a614849',
    messagingSenderId: '681041547372',
    projectId: 'test-370c1',
    authDomain: 'test-370c1.firebaseapp.com',
    storageBucket: 'test-370c1.appspot.com',
    measurementId: 'G-1KSRLQRQ51',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJRvAt9VYRe-U5FqVZ5wXMFDHW0hoyL3U',
    appId: '1:681041547372:android:bdf1f37342903b21614849',
    messagingSenderId: '681041547372',
    projectId: 'test-370c1',
    storageBucket: 'test-370c1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBizW_gC9sv0lMWAcQcK6WVHnfDxJqXk1g',
    appId: '1:681041547372:ios:e41e407a16a8c20f614849',
    messagingSenderId: '681041547372',
    projectId: 'test-370c1',
    storageBucket: 'test-370c1.appspot.com',
    iosBundleId: 'com.example.vicall',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBizW_gC9sv0lMWAcQcK6WVHnfDxJqXk1g',
    appId: '1:681041547372:ios:6495abe54dc33e0b614849',
    messagingSenderId: '681041547372',
    projectId: 'test-370c1',
    storageBucket: 'test-370c1.appspot.com',
    iosBundleId: 'com.example.vicall.RunnerTests',
  );
}
